# Generated by Django 2.2 on 2020-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
