# Generated by Django 2.2 on 2020-06-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_alias_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
